package index

import (
	"fmt"
	"strings"
)

// Options represents the options for an index.
type Options struct {
	Name          string `json:"name"`
	Unique        bool   `json:"unique"`
	Autogenerated bool   `json:"autogenerated"`
}

// NewOptions creates a new index options.
func NewOptions() *Options {
	return &Options{}
}

// SetName sets the name of the index options.
func (o *Options) SetName(name string) *Options {
	o.Name = name

	return o
}

// SetUnique sets the unique flag of the index options.
func (o *Options) SetUnique(unique bool) *Options {
	o.Unique = unique

	return o
}

// Value returns the index options.
func (o *Options) Value() Options {
	return *o
}

// Field represents a field in an index.
type Field struct {
	Name  string `json:"name"`
	Order int    `json:"order"`
}

// Model represents a model for an index.
type Model struct {
	Fields  []Field `json:"fields"`
	Options Options `json:"options"`
}

// NewModel creates a new index model.
func NewModel() *Model {
	return &Model{
		Fields:  make([]Field, 0),
		Options: Options{},
	}
}

// AddField adds a field to the index model.
func (index *Model) AddField(name string, order int) *Model {
	index.Fields = append(index.Fields, Field{Name: name, Order: order})

	return index
}

// SetName sets the name of the index model.
func (index *Model) SetName(name string) *Model {
	index.Options.Name = name

	return index
}

// SetUnique sets the unique flag of the index model.
func (index *Model) SetUnique(unique bool) *Model {
	index.Options.Unique = unique

	return index
}

// Value returns the index model.
func (index *Model) Value() Model {
	return *index
}

// validate checks if the index model is valid.
func (index *Model) validate() error {
	if index.Fields == nil || len(index.Fields) == 0 {
		return ErrEmptyIndexFields
	}

	if strings.TrimSpace(index.Options.Name) == "" {
		name := ""

		for _, f := range index.Fields {
			name += fmt.Sprintf("_%s_%d", f.Name, f.Order)
		}

		index.Options.Name = strings.TrimPrefix(name, "_")
	}

	if index.isCompound() {
		seen := make(map[string]struct{})

		for _, f := range index.Fields {
			if _, ok := seen[f.Name]; ok {
				return ErrDuplicateIndexField
			}
		}
	}

	return nil
}

// isCompound checks if the index model is a compound index.
func (index Model) isCompound() bool {
	return len(index.Fields) > 1
}

// isUnique checks if the index model is unique.
func (index Model) isUnique() bool {
	return index.Options.Unique
}

// isAutogenerated checks if the index model is autogenerated.
func (index Model) isAutogenerated() bool {
	return index.Options.Autogenerated
}

// splitCompoundIndex splits a compound index into multiple single field indexes.
func (index Model) splitCompoundIndex() []Model {
	if index.isCompound() {
		l := (len(index.Fields) * 2)
		results := make([]Model, l)

		for i := range index.Fields {
			// Índice ascendente
			results[i*2] = Model{
				Fields: []Field{
					{Name: index.Fields[i].Name, Order: 1},
				},
				Options: Options{
					Name:          fmt.Sprintf("%s_1", index.Fields[i].Name),
					Autogenerated: true,
				},
			}

			// Índice descendente
			results[i*2+1] = Model{
				Fields: []Field{
					{Name: index.Fields[i].Name, Order: -1},
				},
				Options: Options{
					Name:          fmt.Sprintf("%s_-1", index.Fields[i].Name),
					Autogenerated: true,
				},
			}
		}

		return append(results, index)
	}

	return []Model{index}
}

// splitCompoundIndexes splits all compound indexes in the list.
func splitCompoundIndexes(indexes []Model) []Model {
	results := make([]Model, 0)

	for _, index := range indexes {
		results = append(results, index.splitCompoundIndex()...)
	}

	return results
}
